[package]
name = "cc1352p1f3"
version = "0.1.0"
authors = ["Brandon Matthews <bmatthews@optimaltour.us>"]
edition = "2018"

[dependencies]
bare-metal = "0.2.4"
cortex-m = "0.6.0"
cortex-m-rt = "0.6.7"
vcell = "0.1.0"
